"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const index_1 = require("./index");
const logger = (0, index_1.factory)();
const logger2 = (0, index_1.factory)(undefined, 'Main');
const logger3 = (0, index_1.factory)(undefined, 'Main2', 'MainFunc');
logger.debug('this is test');
logger2.debug('this is test');
logger2.info('this is test');
logger2.warning('this is test');
logger2.error('this is test');
logger3.debug('this is test');
logger2.debug('Main', 'MainFunc2', 'this is test');
logger2.debug('Main', 'MainFunc3', 'this is test', 'subtest');
logger2.warning('Main', 'MainFunc', 'this is warning');
